// Generated by gencpp from file new_code/WordCount.msg
// DO NOT EDIT!


#ifndef NEW_CODE_MESSAGE_WORDCOUNT_H
#define NEW_CODE_MESSAGE_WORDCOUNT_H

#include <ros/service_traits.h>


#include <new_code/WordCountRequest.h>
#include <new_code/WordCountResponse.h>


namespace new_code
{

struct WordCount
{

typedef WordCountRequest Request;
typedef WordCountResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WordCount
} // namespace new_code


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::new_code::WordCount > {
  static const char* value()
  {
    return "58903d21a3264f3408d79ba79e9f7c7e";
  }

  static const char* value(const ::new_code::WordCount&) { return value(); }
};

template<>
struct DataType< ::new_code::WordCount > {
  static const char* value()
  {
    return "new_code/WordCount";
  }

  static const char* value(const ::new_code::WordCount&) { return value(); }
};


// service_traits::MD5Sum< ::new_code::WordCountRequest> should match
// service_traits::MD5Sum< ::new_code::WordCount >
template<>
struct MD5Sum< ::new_code::WordCountRequest>
{
  static const char* value()
  {
    return MD5Sum< ::new_code::WordCount >::value();
  }
  static const char* value(const ::new_code::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::new_code::WordCountRequest> should match
// service_traits::DataType< ::new_code::WordCount >
template<>
struct DataType< ::new_code::WordCountRequest>
{
  static const char* value()
  {
    return DataType< ::new_code::WordCount >::value();
  }
  static const char* value(const ::new_code::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::new_code::WordCountResponse> should match
// service_traits::MD5Sum< ::new_code::WordCount >
template<>
struct MD5Sum< ::new_code::WordCountResponse>
{
  static const char* value()
  {
    return MD5Sum< ::new_code::WordCount >::value();
  }
  static const char* value(const ::new_code::WordCountResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::new_code::WordCountResponse> should match
// service_traits::DataType< ::new_code::WordCount >
template<>
struct DataType< ::new_code::WordCountResponse>
{
  static const char* value()
  {
    return DataType< ::new_code::WordCount >::value();
  }
  static const char* value(const ::new_code::WordCountResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NEW_CODE_MESSAGE_WORDCOUNT_H
